[package]
name = "better-reaction-time"
version = "0.1.0"
edition = "2021"

[dependencies]
relm4 = "0.9"
relm4-components = "0.9"
rand = "0.9.0"
tokio = { version = "1.44.0", features = ["time", "rt"] }
